BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "CATEGORIES" (
	"CategoryID"	INTEGER NOT NULL UNIQUE,
	"CategoryName"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("CategoryID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "DEVELOPERS" (
	"DevID"	INTEGER NOT NULL UNIQUE,
	"DevName"	TEXT NOT NULL UNIQUE,
	"DevSite"	TEXT,
	"DevContact"	TEXT,
	PRIMARY KEY("DevID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "FEATURED" (
	"ID"	INTEGER NOT NULL,
	"APP_ID"	INTEGER,
	FOREIGN KEY("APP_ID") REFERENCES "PACKAGES"("PackageID"),
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "FLAVOUR_TEXT" (
	"TEXT"	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "LICENSES" (
	"LicenseID"	INTEGER NOT NULL UNIQUE,
	"LicenseName"	TEXT NOT NULL UNIQUE,
	"LicenseLink"	TEXT,
	PRIMARY KEY("LicenseID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "PACKAGES" (
	"PackageID"	INTEGER NOT NULL UNIQUE,
	"PrettyName"	TEXT NOT NULL,
	"PackageName"	TEXT NOT NULL UNIQUE,
	"Summary"	TEXT NOT NULL,
	"Description"	TEXT,
	"Developer"	INTEGER NOT NULL,
	"Category"	INTEGER NOT NULL,
	"License"	INTEGER NOT NULL,
	"Confinement"	INTEGER NOT NULL,
	"Icon"	TEXT NOT NULL,
	"Screenshot"	TEXT,
	PRIMARY KEY("PackageID" AUTOINCREMENT),
	FOREIGN KEY("Category") REFERENCES "CATEGORIES"("CategoryID"),
	FOREIGN KEY("Developer") REFERENCES "DEVELOPERS"("DevID"),
	FOREIGN KEY("License") REFERENCES "LICENSES"("LicenseID")
);
CREATE TABLE IF NOT EXISTS "VERSIONS" (
	"VersionID"	INTEGER NOT NULL UNIQUE,
	"VersionName"	TEXT NOT NULL,
	"VersionNumber"	INTEGER NOT NULL,
	"Package"	INTEGER NOT NULL,
	"ReleaseDate"	NUMERIC NOT NULL,
	"DownloadLink"	TEXT NOT NULL,
	"Hash"	TEXT,
	UNIQUE("Package","VersionName"),
	PRIMARY KEY("VersionID" AUTOINCREMENT),
	UNIQUE("VersionNumber","Package"),
	FOREIGN KEY("Package") REFERENCES "PACKAGES"("PackageID")
);
CREATE INDEX "Search" ON "PACKAGES" (
	"PrettyName"
);
COMMIT;
